apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: rasdaman-adapter
  name: rasdaman-adapter
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: rasdaman-adapter
    spec:
      containers:
      - args:
        - start
        env:
        - name: NODE_PATH
          value: app/src
        - name: PORT
          value: "3075"
        - name: API_VERSION
          value: v1
        - name: CT_TOKEN
          value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.IRCIRm1nfIQTfda_Wb6Pg-341zhV8soAgzw7dd5HxxQ
        - name: CT_URL
          value: http://mymachine:9000
        - name: LOCAL_URL
          value: http://mymachine:3075
        name: rasdaman-adapter
        ports:
        - containerPort: 3075
        - containerPort: 35729
        resources: {}
        image: rasdaman-adapter:v1
      restartPolicy: Always
status: {}
